version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - bumpp
  - duckdb
  - heroicons
  - iconify
  - nuxi
  - nuxt
  - nuxtjs
  - shadcn
  - tanstack
  - taze
  - unocss
  - unref
  - vite
  - vueuse
  - webquery
ignoreWords: []
import: []
